language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - echo "Running BeforeInstall"

before_script:
  - echo "Running BeforeScript"
  - composer self-update
  - composer install --no-interaction
  - ./bin/download-codeclimate-reporter.sh

script:
  - echo "RunningScript"
  - composer tests:clover

after_success:
  - echo "Running AfterSuccess"

after_script:
  - echo "Running AfterScript"
  - ./bin/codacycoverage clover clover.xml -vvv
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  fast_finish: false
  allow_failures:
      - php: 7.0
      - php: 7.1
      - php: 7.2

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
